/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChartDataPoint { 'day' : bigint, 'value' : number }
export interface DefectData {
  'defectType' : string,
  'count' : bigint,
  'percentage' : number,
}
export interface Kpi {
  'status' : string,
  'trend' : number,
  'value' : number,
  'name' : string,
  'unit' : string,
}
export interface MaintenanceEvent {
  'status' : string,
  'duration' : number,
  'equipmentName' : string,
  'eventType' : string,
}
export interface PressData {
  'oee' : number,
  'status' : string,
  'output' : number,
  'pressName' : string,
  'recovery' : number,
}
export interface ShiftSummary {
  'oee' : number,
  'output' : number,
  'recovery' : number,
  'shiftName' : string,
}
export interface SummaryStats {
  'oee' : number,
  'activePressCount' : bigint,
  'energyCostPerKg' : number,
  'recovery' : number,
  'totalProductionToday' : number,
  'breakdownHours' : number,
}
export type TimePeriod = { 'today' : null } |
  { 'monthToDate' : null } |
  { 'yearToDate' : null };
export interface _SERVICE {
  'getChartData' : ActorMethod<[string], Array<ChartDataPoint>>,
  'getKpisForDashboard' : ActorMethod<[string, TimePeriod], Array<Kpi>>,
  'getMaintenanceEvents' : ActorMethod<[], Array<MaintenanceEvent>>,
  'getPressWiseData' : ActorMethod<[], Array<PressData>>,
  'getShiftSummaries' : ActorMethod<[], Array<ShiftSummary>>,
  'getSummaryStats' : ActorMethod<[], SummaryStats>,
  'getTopDefects' : ActorMethod<[], Array<DefectData>>,
  'initializeMockData' : ActorMethod<[], undefined>,
  'updateKpi' : ActorMethod<[string, Array<Kpi>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];