/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ChartDataPoint = IDL.Record({
  'day' : IDL.Nat,
  'value' : IDL.Float64,
});
export const TimePeriod = IDL.Variant({
  'today' : IDL.Null,
  'monthToDate' : IDL.Null,
  'yearToDate' : IDL.Null,
});
export const Kpi = IDL.Record({
  'status' : IDL.Text,
  'trend' : IDL.Float64,
  'value' : IDL.Float64,
  'name' : IDL.Text,
  'unit' : IDL.Text,
});
export const MaintenanceEvent = IDL.Record({
  'status' : IDL.Text,
  'duration' : IDL.Float64,
  'equipmentName' : IDL.Text,
  'eventType' : IDL.Text,
});
export const PressData = IDL.Record({
  'oee' : IDL.Float64,
  'status' : IDL.Text,
  'output' : IDL.Float64,
  'pressName' : IDL.Text,
  'recovery' : IDL.Float64,
});
export const ShiftSummary = IDL.Record({
  'oee' : IDL.Float64,
  'output' : IDL.Float64,
  'recovery' : IDL.Float64,
  'shiftName' : IDL.Text,
});
export const SummaryStats = IDL.Record({
  'oee' : IDL.Float64,
  'activePressCount' : IDL.Nat,
  'energyCostPerKg' : IDL.Float64,
  'recovery' : IDL.Float64,
  'totalProductionToday' : IDL.Float64,
  'breakdownHours' : IDL.Float64,
});
export const DefectData = IDL.Record({
  'defectType' : IDL.Text,
  'count' : IDL.Nat,
  'percentage' : IDL.Float64,
});

export const idlService = IDL.Service({
  'getChartData' : IDL.Func([IDL.Text], [IDL.Vec(ChartDataPoint)], ['query']),
  'getKpisForDashboard' : IDL.Func(
      [IDL.Text, TimePeriod],
      [IDL.Vec(Kpi)],
      ['query'],
    ),
  'getMaintenanceEvents' : IDL.Func([], [IDL.Vec(MaintenanceEvent)], ['query']),
  'getPressWiseData' : IDL.Func([], [IDL.Vec(PressData)], ['query']),
  'getShiftSummaries' : IDL.Func([], [IDL.Vec(ShiftSummary)], ['query']),
  'getSummaryStats' : IDL.Func([], [SummaryStats], ['query']),
  'getTopDefects' : IDL.Func([], [IDL.Vec(DefectData)], ['query']),
  'initializeMockData' : IDL.Func([], [], []),
  'updateKpi' : IDL.Func([IDL.Text, IDL.Vec(Kpi)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ChartDataPoint = IDL.Record({ 'day' : IDL.Nat, 'value' : IDL.Float64 });
  const TimePeriod = IDL.Variant({
    'today' : IDL.Null,
    'monthToDate' : IDL.Null,
    'yearToDate' : IDL.Null,
  });
  const Kpi = IDL.Record({
    'status' : IDL.Text,
    'trend' : IDL.Float64,
    'value' : IDL.Float64,
    'name' : IDL.Text,
    'unit' : IDL.Text,
  });
  const MaintenanceEvent = IDL.Record({
    'status' : IDL.Text,
    'duration' : IDL.Float64,
    'equipmentName' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const PressData = IDL.Record({
    'oee' : IDL.Float64,
    'status' : IDL.Text,
    'output' : IDL.Float64,
    'pressName' : IDL.Text,
    'recovery' : IDL.Float64,
  });
  const ShiftSummary = IDL.Record({
    'oee' : IDL.Float64,
    'output' : IDL.Float64,
    'recovery' : IDL.Float64,
    'shiftName' : IDL.Text,
  });
  const SummaryStats = IDL.Record({
    'oee' : IDL.Float64,
    'activePressCount' : IDL.Nat,
    'energyCostPerKg' : IDL.Float64,
    'recovery' : IDL.Float64,
    'totalProductionToday' : IDL.Float64,
    'breakdownHours' : IDL.Float64,
  });
  const DefectData = IDL.Record({
    'defectType' : IDL.Text,
    'count' : IDL.Nat,
    'percentage' : IDL.Float64,
  });
  
  return IDL.Service({
    'getChartData' : IDL.Func([IDL.Text], [IDL.Vec(ChartDataPoint)], ['query']),
    'getKpisForDashboard' : IDL.Func(
        [IDL.Text, TimePeriod],
        [IDL.Vec(Kpi)],
        ['query'],
      ),
    'getMaintenanceEvents' : IDL.Func(
        [],
        [IDL.Vec(MaintenanceEvent)],
        ['query'],
      ),
    'getPressWiseData' : IDL.Func([], [IDL.Vec(PressData)], ['query']),
    'getShiftSummaries' : IDL.Func([], [IDL.Vec(ShiftSummary)], ['query']),
    'getSummaryStats' : IDL.Func([], [SummaryStats], ['query']),
    'getTopDefects' : IDL.Func([], [IDL.Vec(DefectData)], ['query']),
    'initializeMockData' : IDL.Func([], [], []),
    'updateKpi' : IDL.Func([IDL.Text, IDL.Vec(Kpi)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };