/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Kpi {
    status: string;
    trend: number;
    value: number;
    name: string;
    unit: string;
}
export interface SummaryStats {
    oee: number;
    activePressCount: bigint;
    energyCostPerKg: number;
    recovery: number;
    totalProductionToday: number;
    breakdownHours: number;
}
export interface MaintenanceEvent {
    status: string;
    duration: number;
    equipmentName: string;
    eventType: string;
}
export interface PressData {
    oee: number;
    status: string;
    output: number;
    pressName: string;
    recovery: number;
}
export interface ChartDataPoint {
    day: bigint;
    value: number;
}
export interface ShiftSummary {
    oee: number;
    output: number;
    recovery: number;
    shiftName: string;
}
export interface DefectData {
    defectType: string;
    count: bigint;
    percentage: number;
}
export enum TimePeriod {
    today = "today",
    monthToDate = "monthToDate",
    yearToDate = "yearToDate"
}
export interface backendInterface {
    getChartData(chartType: string): Promise<Array<ChartDataPoint>>;
    getKpisForDashboard(dashboard: string, period: TimePeriod): Promise<Array<Kpi>>;
    getMaintenanceEvents(): Promise<Array<MaintenanceEvent>>;
    getPressWiseData(): Promise<Array<PressData>>;
    getShiftSummaries(): Promise<Array<ShiftSummary>>;
    getSummaryStats(): Promise<SummaryStats>;
    getTopDefects(): Promise<Array<DefectData>>;
    initializeMockData(): Promise<void>;
    updateKpi(dashboard: string, newKpis: Array<Kpi>): Promise<void>;
}
import type { TimePeriod as _TimePeriod } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getChartData(arg0: string): Promise<Array<ChartDataPoint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getChartData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChartData(arg0);
            return result;
        }
    }
    async getKpisForDashboard(arg0: string, arg1: TimePeriod): Promise<Array<Kpi>> {
        if (this.processError) {
            try {
                const result = await this.actor.getKpisForDashboard(arg0, to_candid_TimePeriod_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKpisForDashboard(arg0, to_candid_TimePeriod_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getMaintenanceEvents(): Promise<Array<MaintenanceEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMaintenanceEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMaintenanceEvents();
            return result;
        }
    }
    async getPressWiseData(): Promise<Array<PressData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPressWiseData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPressWiseData();
            return result;
        }
    }
    async getShiftSummaries(): Promise<Array<ShiftSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShiftSummaries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShiftSummaries();
            return result;
        }
    }
    async getSummaryStats(): Promise<SummaryStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummaryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummaryStats();
            return result;
        }
    }
    async getTopDefects(): Promise<Array<DefectData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopDefects();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopDefects();
            return result;
        }
    }
    async initializeMockData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeMockData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeMockData();
            return result;
        }
    }
    async updateKpi(arg0: string, arg1: Array<Kpi>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateKpi(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateKpi(arg0, arg1);
            return result;
        }
    }
}
function to_candid_TimePeriod_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimePeriod): _TimePeriod {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TimePeriod): {
    today: null;
} | {
    monthToDate: null;
} | {
    yearToDate: null;
} {
    return value == TimePeriod.today ? {
        today: null
    } : value == TimePeriod.monthToDate ? {
        monthToDate: null
    } : value == TimePeriod.yearToDate ? {
        yearToDate: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
